### ISSUE TITLE
Front End - EventDetails page - create DetailedEventCard component, count me in button, volunteer application 

### ISSUE THREAD

**Issue by natalier97** [crystaljobe/change-mate#111]
![image](https://github.com/crystaljobe/change-mate/assets/154473227/38e01cea-dbe9-4668-a998-b41b690e3a94)
inspiration pic ^^^

leave space for get directions button & location img

**Comment by natalier97** [comment]
- **button** will say "count me in!" --> 2 options "volunteer" || "attend"
- "**attend**" --> will replace rsvp, will add to their changemate calendar & profile feed
- "**volunteer**" --> photo here shows sample application form ----> this will show up as a modal(or separate page if easier??) when a user clicks to volunteer
           > will show which roles are available to sign up for or if none are assigned, maybe wont show any roles?


![Image](https://github.com/crystaljobe/change-mate/assets/154473227/f33f6f84-2d00-42b6-bb73-5b03b0ae8c8f)

**Comment by ReginaFera13** [comment]
Good, but attending doesn't update the model properly anymore due to backend updates
Will have to rework functionality a little
Opened issue #157 to resolve
