### ISSUE TITLE
Frontend - Search Events/Home Feed - Build event details card components

### ISSUE THREAD

**Issue by KaraWatts** [crystaljobe/change-mate#12]
Build card components to display event details for search events page and home feed.

Details should include:
- Date/Time
- Location
- Event Title
- Brief Description???

**Comment by natalier97** [comment]
**********TESTING**
- event Details card on profile page & event details page are rendering proper information
- needs testing on search Events page
@ReginaFera13 i believe this would be a good one for you to test on searchEvents page
