### ISSUE TITLE
Backend - UserProfile Location Model Updated to take Array of Strings - Wait for #118

### ISSUE THREAD

**Issue by crystaljobe** [crystaljobe/change-mate#120]
Dependency - #118 
Need to confirm format before changing backend model to match front end data

Model needs to be reworked to store array of objects for user location ex - [{country: 'United States', state: 'Colorado', city: 'Colorado Springs'}, {country: 'United States', state: 'Colorado', city: 'Denver'}]

Edit profile put method needs to have the error updated

![Image](https://github.com/crystaljobe/change-mate/assets/141180011/121b3a43-84c3-4599-a2ce-a6a1e8b8f8a2)

**Comment by KaraWatts** [comment]
https://countrystatecity.in/docs/

integrate this api into the backend to make the calls

**Comment by KaraWatts** [comment]
jsonify and save input as string to allow for search and save in textfield
