### ISSUE TITLE
Frontend - Create Event Admin Page Skeleton

### ISSUE THREAD

**Issue by crystaljobe** [crystaljobe/change-mate#123]
EVENT ADMIN PAGE - page for managing the event - need wireframe and page skeleton for Event Admin Page

**User access** 
- Hosts only (host should have "admin" permission"

**features:** 
- [ ] add other hosts 
- [ ] accept volunteer applications 
- [ ] create todo lists tasks
- [ ] assign volunteers to the tasks

**Comment by KaraWatts** [comment]
Volunteer Roles API data found on #144
