### ISSUE TITLE
Frontend - Create Side Navbar To Allow Users to Navigate to Event Admin Page, Event Collaboration Page

### ISSUE THREAD

**Issue by crystaljobe** [crystaljobe/change-mate#129]
Navbar should be in a collapsable menu interface style that allows the following navigation: 

**Users with "Admin" permissions:** 
- [ ] Navigate to Event Admin Page
- [ ] Navigate to Event Collaboration page 

**Users with "Volunteer" permissions:**
- [ ] Navigate to Event Collaboration page

**Comment by KaraWatts** [comment]
This should not be visible to standard users.
