### ISSUE TITLE
Frontend - Create/Edit Event - Update Create/Edit Event Page location input

### ISSUE THREAD

**Issue by ReginaFera13** [crystaljobe/change-mate#141]
Update Create/Edit Event Page to set a general location in this format: 
       - [{country: 'United States', state: 'Colorado', city: 'Colorado Springs'}]
       - convert to json string before sending it to backend

**Comment by crystaljobe** [comment]
Hey @ReginaFera13  just for clarification on this issue -

Are you saying we just need to update the way the data is getting sent to the backend? If that's the case I can add to the map component to add the country and then I'll let you add the json and parsing as you need it. 

I just want to make sure this isn't meaning we're overriding the current mapbox location component and functionality.
