### ISSUE TITLE
Backend - Admin Page - GET request to receive userProfile info when searching by email

### ISSUE THREAD

**Issue by natalier97** [crystaljobe/change-mate#159]
- admin needs to be able to _search by user email_ & receive back **user Profile info** (obj that contains {id, display_name, image, user_events[{arr of event Objs that user is a collaborator/host of}] } )
-

**Comment by KaraWatts** [comment]
@natalier97 what data do you want for the event details? just title and id for the link?

**Comment by KaraWatts** [comment]
Not going to worry about event data but will add validator to prevent hosts being added twice.
