### ISSUE TITLE
Frontend - Create Event Collaboration Page Skeleton

### ISSUE THREAD

**Issue by ReginaFera13** [crystaljobe/change-mate#59]
Could be on the event details page or a button on the even details page that leads to the collaboration page
People can like the event
People can comment on the event
To-do list

**Comment by crystaljobe** [comment]
![Image](https://github.com/crystaljobe/change-mate/assets/144761681/d3e67d2d-df8c-40b2-9e22-461e7ea49633)

**Comment by crystaljobe** [comment]
EVENT COLLABORATION PAGE

- [ ] Page for Event Planning
- [ ] User access: HOSTS & VOLUNTEERS only

**Comment by KaraWatts** [comment]
Volunteer Roles API data found on https://github.com/crystaljobe/change-mate/pull/144
