### ISSUE TITLE
Backend - Volunteers - Allow users to volunteer for events

### ISSUE THREAD

**Issue by KaraWatts** [crystaljobe/change-mate#67]
Create and store user volunteer applications in volunteer application model and ensure it's connected to volunteer roles.

![Image](https://github.com/crystaljobe/change-mate/assets/142848456/5b5abac1-a5fe-42b7-8d0c-2ac557a6cba3)

**Comment by adamcee** [comment]
Allow Users to Volunteer for Events

A logged-in user is able to:

- View an Event on the Event Details Page
- Click on a button to Sign Up to Volunteer for the Event. 
- The database is updated accordingly. **TBD: What Model gets updated.** 
- The User receives some sort of feedback in the app that they've signed up for the event (message, popup, etc).

**Comment by crystaljobe** [comment]
A logged in user is able to: 

[ ] - User searches for event 
[ ] - User finds an event that needs volunteers 
[ ] - User clicks on Event Details button to navigate them to see more details
[ ] - User clicks Volunteer Sign-up Button 
[ ] - User sees List of Roles Available and Volunteer Application to Fill out and Submit 
[ ] - User gets alert saying their application has been submitted and is pending approval
[ ] - Upon submit user sees Event Detail page again
[ ] - Application will be sent to Event Host Inbox for approval 
[ ] - User profile will display a “Volunteer Events” section with a status of their application
[ ] - User gets approved for volunteering - they get access to Event Collaboration page
