### ISSUE TITLE
Refactor Create Event/Edit Event pages to be one page with component imports to a singular page

### ISSUE THREAD

**Issue by crystaljobe** [crystaljobe/change-mate#88]
Edit Event Page and Create Event page could be refactored to one singular page to make all the code more efficient and easier to update to avoid having to update two separate pages with the same functionality aspects.

**Comment by natalier97** [comment]
***********TESTING** everything seems good except the virtualevent link not populating when trying to edit a virtual event, but we already have an issue out for that. @LouisMartin07 

i was able to create an event, but i did get this message on the django-side of things. i let @KaraWatts know already, unsure if it's problematic or not.
![Image](https://github.com/crystaljobe/change-mate/assets/154473227/2045e32f-4374-4deb-bb91-95765421dab4)
